'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { DemoRequestModal } from '@/components/demo-request-modal'
import { ArrowRightIcon, CalendarDaysIcon, ShieldCheckIcon, SparklesIcon } from '@heroicons/react/24/outline'

export default function Home() {
  const [isDemoModalOpen, setIsDemoModalOpen] = useState(false)
  const appointments = ['09:00  •  Jamie Williams', '10:30  •  Mark Johnson', '11:15  •  Priya Shah']

  return (
    <main className="min-h-screen overflow-hidden bg-[#f6f9fc] text-slate-950">
      <DemoRequestModal open={isDemoModalOpen} onClose={() => setIsDemoModalOpen(false)} />
      <section className="relative">
        <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_75%_10%,rgba(14,165,233,0.16),transparent_30%),linear-gradient(180deg,#f8fbff_0%,#eef7fa_100%)]" />
        <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-8">
          <Link href="/" className="flex items-center gap-3" aria-label="ClinicEase home"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-xl font-bold text-cyan-300">+</span><span className="text-lg font-bold tracking-tight">ClinicEase <span className="text-cyan-600">AI</span></span></Link>
          <div className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex"><Link href="/pricing" className="hover:text-slate-950">Solutions</Link><Link href="/about" className="hover:text-slate-950">About</Link><Link href="/contact" className="hover:text-slate-950">Contact</Link></div>
          <Link href="/login?role=staff" className="text-sm font-semibold text-slate-700 hover:text-cyan-700">Sign in <ArrowRightIcon className="ml-1 inline h-4 w-4" /></Link>
        </nav>
        <div className="relative z-10 mx-auto grid max-w-7xl items-center gap-14 px-6 pb-24 pt-14 lg:grid-cols-[1fr_0.9fr] lg:px-8 lg:pb-32 lg:pt-20">
          <div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-cyan-200 bg-white/70 px-4 py-2 text-sm font-semibold text-cyan-800 shadow-sm"><SparklesIcon className="h-4 w-4" /> A clearer way to care</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.04] tracking-[-0.04em] text-slate-950 sm:text-6xl lg:text-7xl">Your clinic, <span className="text-cyan-600">working beautifully.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">ClinicEase brings appointments, patients, billing, and communication into one calm, intelligent workspace.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/login?role=staff"><Button size="lg" className="h-13 rounded-xl bg-slate-950 px-7 text-base text-white hover:bg-slate-800">Explore the platform <ArrowRightIcon className="ml-2 h-5 w-5" /></Button></Link><Button size="lg" variant="outline" className="h-13 rounded-xl border-slate-300 bg-white/70 px-7 text-base" onClick={() => setIsDemoModalOpen(true)}>Book a demo</Button></div><div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-600"><span className="flex items-center gap-2"><ShieldCheckIcon className="h-5 w-5 text-cyan-600" /> Secure by design</span><span className="flex items-center gap-2"><CalendarDaysIcon className="h-5 w-5 text-cyan-600" /> Less admin work</span></div></div>
          <div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-6 rounded-[2.5rem] bg-cyan-200/40 blur-3xl" /><div className="relative rounded-[2rem] border border-white bg-white p-4 shadow-[0_24px_80px_rgba(15,23,42,0.14)]"><div className="flex items-center justify-between border-b border-slate-100 px-3 pb-4"><div><p className="text-xs font-medium text-slate-400">TUESDAY, OCTOBER 8</p><p className="mt-1 text-lg font-bold">Good morning, Dr. Lee</p></div><div className="h-9 w-9 rounded-full bg-cyan-100 text-center leading-9 font-bold text-cyan-700">DL</div></div><div className="grid grid-cols-3 gap-3 py-4"><div className="rounded-xl bg-slate-950 p-3 text-white"><p className="text-xs text-slate-400">Today&apos;s visits</p><p className="mt-2 text-2xl font-bold">18</p></div><div className="rounded-xl bg-cyan-50 p-3"><p className="text-xs text-cyan-700">New patients</p><p className="mt-2 text-2xl font-bold text-slate-900">06</p></div><div className="rounded-xl bg-amber-50 p-3"><p className="text-xs text-amber-700">To review</p><p className="mt-2 text-2xl font-bold text-slate-900">04</p></div></div><div className="rounded-xl border border-slate-100 p-4"><div className="mb-4 flex items-center justify-between"><p className="font-bold">Upcoming appointments</p><span className="text-xs font-semibold text-cyan-700">View all</span></div>{appointments.map((item, i) => <div key={item} className="flex items-center gap-3 border-t border-slate-100 py-3 text-sm"><span className={`h-2 w-2 rounded-full ${i === 1 ? 'bg-amber-400' : 'bg-cyan-500'}`} /><span className="font-medium text-slate-700">{item}</span><span className="ml-auto text-xs text-slate-400">{i === 1 ? 'Follow-up' : 'Consultation'}</span></div>)}</div></div></div>
        </div>
      </section>
      <section className="border-y border-slate-200 bg-white px-6 py-16 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-center text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">One platform for the whole practice</p><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-slate-950 p-7 text-white"><p className="text-sm font-semibold text-cyan-300">01 / Schedule</p><h2 className="mt-8 text-2xl font-bold">Keep every appointment moving.</h2><p className="mt-3 leading-7 text-slate-300">Simple scheduling that keeps your team and patients in sync.</p></div><div className="rounded-2xl bg-cyan-50 p-7"><p className="text-sm font-semibold text-cyan-700">02 / Understand</p><h2 className="mt-8 text-2xl font-bold">See the full patient story.</h2><p className="mt-3 leading-7 text-slate-600">Bring records, notes, and conversations together when it matters.</p></div><div className="rounded-2xl bg-amber-50 p-7"><p className="text-sm font-semibold text-amber-700">03 / Grow</p><h2 className="mt-8 text-2xl font-bold">Spend time where it counts.</h2><p className="mt-3 leading-7 text-slate-600">Automate the busywork and give your team room to deliver better care.</p></div></div></div></section>
      <section className="bg-slate-950 px-6 py-20 text-center text-white lg:px-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Ready when you are</p><h2 className="mx-auto mt-5 max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl">Make the next day at your clinic feel lighter.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-slate-300">Start with a better view of your practice today.</p><div className="mt-8"><Link href="/login?role=staff"><Button size="lg" className="rounded-xl bg-cyan-400 px-7 text-slate-950 hover:bg-cyan-300">Get started <ArrowRightIcon className="ml-2 h-5 w-5" /></Button></Link></div></section>
      <footer className="flex flex-col items-center justify-between gap-4 bg-white px-6 py-8 text-sm text-slate-500 sm:flex-row lg:px-8"><span className="font-bold text-slate-900">ClinicEase AI</span><div className="flex gap-5"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/contact">Contact</Link></div></footer>
    </main>
  )
}
